// This is the main entry point for the React Native app when we use shadow-cljs to build the JS bundle.
// When we used Krell, the index file was generated by Krell itself. 
// Krell build was used till OneKeePass Mobile v0.17.0 

// A RN sample app uses index.js, App.tsx and app.json as the main entry points.
// Krell used index.js and app.json
// shadow-cljs uses only the index.js as the main entry point.

// RN Metro bundler looks for index.js as the entry point for the main app and also android autofill.
import './src-cljs/cljs-main-app-out/index.js';