# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OneKeePassMobile' do
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # hermes_enabled is set false for Cljs compiled code to work - Jey
    # We can use export USE_HERMES=0 to set hermes_enabled false by env variable 
    # before running pod install - Jey
    :hermes_enabled => false,

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Added after introducing autofill extension
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
    
  end
end


target 'OneKeePassAutoFill' do
  
  ## Some references:
  # https://github.com/react-native-community/cli/issues/1179#issuecomment-756539463
  # https://github.com/codibly/app-clip-instant-app-react-native/blob/main/Handling-Size-React-Native-AppClip.md
  # https://gist.github.com/ridvanaltun/a02a9a8a8d4bbd354a5cd875a20cf21f
  
  # https://github.com/react-native-community/cli/blob/v15.0.1/docs/autolinking.md#platform-ios
  # react-native-community/cli v15.0.1 is used with RN 0.78.2
  
  ## ** This worked till RN 0.74.5 and did not work with RN 0.78.2 upgrade **
  
  # Requires a patching in
  # /node_modules/@react-native-community/cli-platform-ios/native_modules.rb
  # to use 'packages_to_skip'
  # config = use_native_modules!(packages_to_skip:['RNBootSplash', 'RNCClipboard','RNReanimated','RNFileViewer', 'VisionCamera','RNVectorIcons'])
  
  
  ## ** After RN 0.78.2 upgrade, we need make changes in /node_modules/react-native/scripts/cocoapods/autolinking.rb **
    
  # Require a patching of /node_modules/react-native/scripts/cocoapods/autolinking.rb where we skip some native module packages
  # The following ENV varable OKP_AUTOFILL_TARGET is used to identify the autofill target so that skipping of the pods
  # are considered for this target only

  ENV['OKP_AUTOFILL_TARGET'] = "true"
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
end
