###############################   Shadow-cljs     ######################################

alias shcr := shadow-cljs-clean-watch
alias shexcr := shadow-cljs-ios-ext-clean-watch 

alias shre := shadow-cljs-clean-release
alias shexre := shadow-cljs-ios-ext-clean-release

shadow_cljs_version := "3.3.5"

shadow-cljs-clean-watch:
    rm -rf cljs-main-app-out
    npx shadow-cljs@{{shadow_cljs_version}} watch app  

shadow-cljs-ios-ext-clean-watch:
    rm -rf cljs-ios-autofill-out
    npx shadow-cljs@{{shadow_cljs_version}} watch ios-autofill

shadow-cljs-clean-release:
    rm -rf cljs-main-app-out
    npx shadow-cljs@{{shadow_cljs_version}} release app  

shadow-cljs-ios-ext-clean-release:
    rm -rf cljs-ios-autofill-out
    npx shadow-cljs@{{shadow_cljs_version}} release ios-autofill
   

###############################  End Shadow-cljs  ######################################

